using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace GAPA
{
    public partial class Portoes_G : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {

            if (Session["tipo"] == null || !Session["tipo"].Equals("Administrador"))
                Response.Redirect("login.aspx");


            Page.Title = "Gerir Portões - GAPA";
            //consulta a bd
            DataTable dados = BaseDados.Instance.listarDataTablePortoes();
            if (dados == null || dados.Rows.Count == 0) return;
            if (!IsPostBack) {
            //    atualizarGv(dados);
                }

            gvPortoes.RowEditing += new GridViewEditEventHandler(this.gvPortoes_RowEditing);
            gvPortoes.RowCancelingEdit += new GridViewCancelEditEventHandler(this.gvPortoes_RowCancelingEdit);
            gvPortoes.RowUpdating += new GridViewUpdateEventHandler(this.gvPortoes_RowUpdating);
           gvPortoes.RowDeleting += new GridViewDeleteEventHandler(this.gvPortoes_RowDeleting);


        }

        private void gvPortoes_RowDeleting(object sender, GridViewDeleteEventArgs e)
        {
            int linha = e.RowIndex;
            string id = gvPortoes.Rows[linha].Cells[1].Text;
            BaseDados.Instance.removerPortao(int.Parse(id));
            //atualizar grelha
            if (String.IsNullOrEmpty(tbPesquisa.Text))
                //  atualizarGv();
                pesquisa();
            else
            {
                string text = tbPesquisa.Text;
                DataTable dados = BaseDados.Instance.pesquisarPortoes(text);
                //       atualizarGv(dados);
                pesquisa();

            }
        }

        private void gvPortoes_RowUpdating(object sender, GridViewUpdateEventArgs e)
        {
            int linha = e.RowIndex;
            Portoes portao = new Portoes();
            portao.id = int.Parse(gvPortoes.Rows[linha].Cells[1].Text);
            portao.nome = ((TextBox)gvPortoes.Rows[linha].Cells[2].Controls[0]).Text;
            portao.ip = ((TextBox)gvPortoes.Rows[linha].Cells[3].Controls[0]).Text;
            portao.captura = ((CheckBox)gvPortoes.Rows[linha].Cells[4].Controls[0]).Checked;
            portao.camera = int.Parse(((TextBox)gvPortoes.Rows[linha].Cells[5].Controls[0]).Text);
            portao.ativo = ((CheckBox)gvPortoes.Rows[linha].Cells[6].Controls[0]).Checked;
          
            BaseDados.Instance.atualizarPortao(portao);

            gvPortoes.EditIndex = -1;
            if (String.IsNullOrEmpty(tbPesquisa.Text))
                atualizarGv();
            else
            {
                string text = tbPesquisa.Text;
                DataTable dados = BaseDados.Instance.pesquisarPortoes(text);
                //       atualizarGv(dados);
                pesquisa();
            }
        }

        private void gvPortoes_RowCancelingEdit(object sender, GridViewCancelEditEventArgs e)
        {
            gvPortoes.EditIndex = -1;
            if (String.IsNullOrEmpty(tbPesquisa.Text))
                //     atualizarGv(); 
                pesquisa();
            else
            {
                string text = tbPesquisa.Text;
                DataTable dados = BaseDados.Instance.pesquisarPortoes(text);
                // atualizarGv(dados);
                pesquisa();
            }
        }

        private void gvPortoes_RowEditing(object sender, GridViewEditEventArgs e)
        {
            int linha = e.NewEditIndex;
            gvPortoes.EditIndex = linha;

            if (String.IsNullOrEmpty(tbPesquisa.Text))
                //    atualizarGv();
                pesquisa();
            else
            {
                string text = tbPesquisa.Text;
                DataTable dados = BaseDados.Instance.pesquisarPortoes(text);
                //   atualizarGv(dados);
                pesquisa();
            }
        //    ((TextBox)gvPortoes.Rows[linha].Cells[1].Controls[0]).Enabled = false;
         
        
        }

        private void atualizarGv(DataTable dados)
        {
            //limpar grid
            gvPortoes.Columns.Clear();


            gvPortoes.DataSource = dados;
            gvPortoes.AutoGenerateColumns = true;
            gvPortoes.AutoGenerateDeleteButton = true;
            gvPortoes.AutoGenerateEditButton = true;
            gvPortoes.DataBind();
        }
        private void atualizarGv()
        {
            //limpar grid
            DataTable dados = BaseDados.Instance.listarDataTablePortoes();
            gvPortoes.Columns.Clear();


            gvPortoes.DataSource = dados;
            gvPortoes.AutoGenerateColumns = true;
            gvPortoes.AutoGenerateDeleteButton = true;
            gvPortoes.AutoGenerateEditButton = true;
            gvPortoes.DataBind();
        }

        protected void btPesquisa_Click(object sender, EventArgs e)
        {
            string text = tbPesquisa.Text;
            DataTable dados = BaseDados.Instance.pesquisarPortoes(text);
            //  atualizarGv(dados);
            gvPortoes.DataSourceID = "";
            gvPortoes.DataSource = dados;
            gvPortoes.DataBind();

        }

        protected void pesquisa()
        {

            string text = tbPesquisa.Text;


            DataTable dados;
            if (!String.IsNullOrEmpty(text))
            {
               dados = BaseDados.Instance.pesquisarPortoes(text);
                if (dados.Rows.Count == 0 || dados == null)
                {
                    dados = BaseDados.Instance.listarDataTablePortoes();
                    tbPesquisa.Text = "";
                }
            }
            else
            {
              dados = BaseDados.Instance.listarDataTablePortoes();
                tbPesquisa.Text = "";
            }

            gvPortoes.DataSourceID = "";
            gvPortoes.DataSource = dados;
            gvPortoes.DataBind();
        }

    }
}